#!/bin/bash  
# #
# Description
#
#
##
if [ $DEBUG = true ]; then
   echo "Installing utility software";
fi
apt-get -y install ssh
apt-get -y install git
apt-get -y install wget
apt-get -y install zip
apt-get -y install rsync
apt-get -y install curl
apt-get -y install vim
