#!/bin/bash  
# #
# Description
#
#
##
        
##
# Global variables
##
DEINSTALL=$1;

##
# Global directory path
##
DIR="${BASH_SOURCE%/*}"
if [ $DEBUG = true ]; then
   echo "Directory path $DIR";
   
fi

##
# Get config installation variables
##
source "${DIR}/config"

##
# Show debug
##
if [ $DEBUG = true ]; then
   echo "Debug is on";
   
fi


##
# Install or deinstall software
##
if [ "${DEINSTALL}" = "-d" ]; then
   echo "Deinstalling software";
   source "${DIR}/src/custom/purge_software"
   source "${DIR}/src/contrib/purge_software"
   source "${DIR}/src/debs/purge_software"
else
   echo "Installing software"
   source "${DIR}/src/debs/install_software"
   source "${DIR}/src/contrib/install_software"
   source "${DIR}/src/custom/install_software"
fi
 

