#!/bin/bash  
# #
# Description
#
#
##
if [ $DEBUG = true ]; then
    echo "Install Nextcloud and plugins";
fi

git clone --depth=1 https://github.com/nextcloud/server.git /var/www/html/apps/nextcloud
