#!/bin/bash  
# #
# Description
#
#
##


##
#  Web server software
##
if [ "${WEBSERVER}" = "" ]; then
   echo "No webserver software been selected";
fi

if [ "${WEBSERVER}" = "lamp" ]; then
   echo "Installing Lamp";
   apt-get install apache2 -y
 
fi

if [ "${WEBSERVER}" = "limp" ]; then
   echo "Installing Nginx";
   apt-get install nginx -y
fi

##
#  Mysql software
##
apt-get -y install mariadb-server mariadb-client
mysql_secure_installation <<EOF

${mysql_area[1]}
${mysql_area[2]}
${mysql_area[3]}
${mysql_area[4]}
${mysql_area[5]}
${mysql_area[6]}
EOF

##
# Php installation
##
apt-get -y install php7.0 libapache2-mod-php7.0
apt-get -y install php7.0-mysql php7.0-curl php7.0-gd php7.0-intl php-pear php-imagick php7.0-imap php7.0-mcrypt php-memcache  php7.0-pspell php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-mbstring php-gettext
apt-get -y install php-apcu
