#!/bin/bash  
# #
# Description
#
#
##

##
# Show debug
##
if [ $DEBUG = true ]; then
   echo "Installing debs software";
fi

apt-get update
#source "${DIR}/src/debs/utilities/install";
source "${DIR}/src/debs/lamp/install";
#source "${DIR}/src/debs/lets_encrypt/install";
