#!/bin/bash  
# #
# Description
#
#
##

##
# Show debug
##
if [ $DEBUG = true ]; then
   echo "Purge debs software";
fi


source "${DIR}/src/debs/utilities/deinstall";
source "${DIR}/src/debs/lamp/deinstall";
source "${DIR}/src/debs/lets_encrypt/deinstall";


##
# Auto remove
##
apt-get -y autoremove;
 
