#!/bin/bash  
# #
# Description
#
#
##
if [ $DEBUG = true ]; then
   echo "Install lets encrypt";
fi
apt-get -y install python-letsencrypt-apache
letsencrypt --apache -d ${BASEDOMAIN}

##
# Add cron job to update lets encrypt
##
croncmd="/usr/bin/letsencrypt renew >> /var/log/le-renew.log"
cronjob="30 2 * * 1  $croncmd"
( crontab -l ; echo "$cronjob" ) | crontab -

