#!/bin/bash  
# #
# Description
#
#
##

##
# Show debug
##
if [ $DEBUG = true ]; then
   echo "Purge contrib software";
fi
source "${DIR}/src/contrib/structure/deinstall";
source "${DIR}/src/contrib/composer/deinstall";

#source "${DIR}/src/contrib/drupal_cli/deinstall";
