#!/bin/bash  
# #
# Description
#
#
##
if [ $DEBUG = true ]; then
    echo "Install composer";
fi
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
